version: '3'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: make run
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root  # TODO: make this a secret
      - MYSQL_HOST=mysql

  mysql:
    image: mysql:8.2.0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
