# Generated by Django 4.2.5 on 2023-10-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cast_member_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="castmember",
            name="cast_member_type",
            field=models.CharField(choices=[("director", "Director"), ("actor", "Actor")], max_length=255),
        ),
    ]
