# Generated by Django 4.2.5 on 2023-10-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0003_delete_genrecategory"),
        ("genre_django_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenreCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_app.category")),
                ("genre", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="genre_django_app.genre")),
            ],
        ),
    ]
