# Generated by Django 4.2.5 on 2023-10-16 19:09

import core.cast_member.domain.entity.cast_member
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "cast_member_type",
                    models.CharField(
                        choices=[
                            (core.cast_member.domain.entity.cast_member.CastMemberType["DIRECTOR"], "director"),
                            (core.cast_member.domain.entity.cast_member.CastMemberType["ACTOR"], "actor"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
