# Generated by Django 4.2.5 on 2023-10-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cast_member_app", "0004_alter_castmember_cast_member_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="castmember",
            name="cast_member_type",
            field=models.CharField(choices=[("DIRECTOR", "director"), ("ACTOR", "actor")], max_length=255),
        ),
    ]
