# Generated by Django 4.2.5 on 2023-10-26 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_genrecategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenreCategory",
        ),
    ]
